# Generated by Django 3.2.7 on 2024-01-25 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0004_blog_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='blog',
            name='likedusers',
            field=models.ManyToManyField(related_name='liked_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
